services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:8761 || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - storytail-network

  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d authdb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - storytail-network

  postgres-profile:
    image: postgres:16
    container_name: postgres-profile
    environment:
      POSTGRES_DB: profiledb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - profile-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d profiledb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - storytail-network

  postgres-story:
    image: postgres:16
    container_name: postgres-story
    environment:
      POSTGRES_DB: storydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5434:5432"
    volumes:
      - story-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d storydb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - storytail-network

  postgres-notification:
    image: postgres:16
    container_name: postgres-notification
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5435:5432"
    volumes:
      - notification-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d notificationdb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - storytail-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres-auth:
        condition: service_healthy
    networks:
      - storytail-network

volumes:
  auth-data:
  profile-data:
  story-data:
  notification-data:

networks:
  storytail-network:
    driver: bridge
