spring:
  application:
    name: eureka-server

# Eureka Server Configuration
# Set the port for the Eureka server
server:
  port: 8761

#Register name in Eureka Servers
eureka:
  instance:
    hostname: eureka-server
  client:
 #Einsure that the Eureka server does not try to self-register 
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
    
